<?php

namespace Semantics\RatingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CorpusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorpusRepository extends EntityRepository
{

}
