<?php

namespace Semantics\RatingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReviewWordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpressionWordRepository extends EntityRepository
{

}
