<?php

namespace Semantics\RatingBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Semantics\RatingBundle\Interfaces\SemanticEntityHolder;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ExpressionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpressionRepository extends EntityRepository
{
    /**
     *
     *
     * @param RegistryInterface $orm
     * @param SemanticEntityHolder $entity
     * @return SemanticEntityHolder
     */
    public function save(RegistryInterface $orm, SemanticEntityHolder $entity)
    {
        $existingEntity = $this->findOneBy(['reviewId' => $entity->getReviewId(), 'hash' => $entity->getHash()]);
        if (!$existingEntity instanceof SemanticEntityHolder) {
            $orm->getManager()->persist($entity);
            $orm->getManager()->flush();
            return $entity;
        }
        $existingEntity->copy($entity);
        //print_r($entity->toArray());
        //die;
        //die(get_class($existingEntity) . "-->" . $existingEntity->getReviewId());
        //$existingEntity->setReviewId($entity->getReviewId());
        //$existingEntity->setScore($entity->getScore());
        $orm->getManager()->flush();
        return $existingEntity;
        /* $existingEntity->copy($entity);
          $orm->getManager()->persist($existingEntity);
          $orm->getManager()->flush();
          var_dump($existingEntity->toArray());
          die;
          return $existingEntity; */
    }
}
