<?php

namespace Semantics\RatingBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Semantics\RatingBundle\Interfaces\SemanticEntityHolder;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * CorpusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordRepository extends EntityRepository
{
    /**
     *
     *
     * @param RegistryInterface $orm
     * @param SemanticEntityHolder $entity
     * @return SemanticEntityHolder
     */
    public function fetch(RegistryInterface $orm, SemanticEntityHolder $entity)
    {
        $existingEntity = $this->findOneBy(['word' => $entity->getWord()]);
        if (!$existingEntity instanceof SemanticEntityHolder) {
            $orm->getManager()->persist($entity);
            $orm->getManager()->flush();
            return $entity;
        }
        $existingEntity->copy($entity);
        $orm->getManager()->flush();
        return $existingEntity;
    }
}
