rating:
    resource: "@RatingBundle/Resources/config/routing.yml"
    prefix:   /

review:
    resource: "@ReviewBundle/Resources/config/routing.yml"
    prefix:   /

criteria:
    resource: "@CriteriaBundle/Resources/config/routing.yml"
    prefix:   /
