RatingBundle:
    resource: "@RatingBundle/Controller/RatingController.php"
    type:     annotation
thrace_data_grid:
    resource: "@ThraceDataGridBundle/Resources/config/routing.xml"
    prefix:   /
