Rating:
    resource: "@RatingBundle/Controller/RatingController.php"
    type:     annotation
Review:
    resource: "@RatingBundle/Controller/ReviewController.php"
    type:     annotation
Criteria:
    resource: "@RatingBundle/Controller/CriteriaController.php"
    type:     annotation