services:
    CurlService:
        class: anlutro\cURL\cURL
    PorterStemmer:
        class: Semantics\RatingBundle\Services\PorterStemmer
    MorphAdorner:
        class: Semantics\RatingBundle\Services\MorphAdorner
        arguments: ["@doctrine", "@CurlService", "@PorterStemmer", "@logger"]
    RepositoryBuilder:
        class: Semantics\RatingBundle\Services\RepositoryBuilder
    DoctrinePersister:
        class: Semantics\RatingBundle\Services\DoctrinePersister
        arguments: ["@Doctrine", "@MorphAdorner", "@RepositoryBuilder", "@logger"]
    ReviewAnalyzer:
        class: Semantics\RatingBundle\Services\ReviewAnalyzer
    SemanticApp:
        class: Semantics\RatingBundle\Services\SemanticApp
        arguments: ["@DoctrinePersister", "@ReviewAnalyzer"]
    app.datagrid.builder.topic_management:
        class: Semantics\RatingBundle\Services\Datagrid\TopicManagementBuilder
        arguments: ["@thrace_data_grid.factory.datagrid", "@translator", "@router", "@doctrine.orm.entity_manager"]
    app.datagrid.topic_management:
        class: Thrace\DataGridBundle\DataGrid\DataGrid
        factory: ['@app.datagrid.builder.topic_management', build]
        tags:
            - { name: thrace_data_grid.datagrid, alias: topic_management }