<?php

namespace Semantics\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReviewWordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewWordRepository extends EntityRepository
{

}
